CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    nickname VARCHAR(255) UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(255) UNIQUE,
    password VARCHAR(600) NOT NULL,
    role VARCHAR(100) NOT NULL,
    level VARCHAR(256),
    is_email_verified BOOLEAN,
    is_phone_number_verified BOOLEAN,
    is_2fa_enabled BOOLEAN,
    sol_balance BIGINT,
    created TIMESTAMP,
    modified TIMESTAMP
);

INSERT INTO public.users(
	user_id, nickname, first_name, last_name, email, password, role, level, is_email_verified, sol_balance, created, modified)
	VALUES (1, 'postullat', 'Volodymyr', 'Bondarchuk', 'postullat2@gmail.com', '$2a$10$BvupiBaiiNLxcc8FErqUzuWoR6Dys/RQzOsrNE9zC9/GancwPrQaG', 'PLAYER, ADMIN', 'Bronze', true, 0, '2024-04-05 13:56:16.103013', '2024-04-05 13:56:16.103013');


CREATE TABLE games (
    game_id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    outcome VARCHAR(10),
    created TIMESTAMP,
    modified TIMESTAMP,
    CONSTRAINT fk_games_user_id FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE auth_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expiration_date TIMESTAMP,
    token VARCHAR(255),
    otp VARCHAR(255),
    user_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_auth_tokens_users_id FOREIGN KEY (user_id) REFERENCES users(user_id)
);